media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [title, draft, pubDatetime]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - { name: pubDatetime, label: Publish Date, type: date, required: true }
      - { name: modDatetime, label: Modified Date, type: date }
      - { name: author, label: Author, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: ogImage, label: OG Image, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text }
